// El seed siempre crea el equipo del usuario como el primer registro
// (id=1, gracias a RESTART IDENTITY en el TRUNCATE).
module.exports = {
  USER_TEAM_ID: 1,
  PRE_SEASON_DAYS: 15,
  ROSTER_CHECK_DAY: 15, // mismo valor que PRE_SEASON_DAYS por diseno: ultimo dia de pre-temporada
  PLAYER_INVESTMENT_DAY: 14, // 2 dias antes del inicio de temporada regular (dia 16 = PRE_SEASON_DAYS + 1)
  OFFER_WINDOW_END_DAY: 3,
  GAMES_PER_SEASON: 30,
  MAX_ROSTER_SIZE: 25,
  MAX_MINOR_ROSTER_SIZE: 15,
  AUCTION_DEADLINE_DAY: 30,
  DRAFT_POOL_SIZE: 100,
  MARKET_PLAYER_CAP: 1250,
  LUXURY_TAX_PROJECTION_DAY: 30, // mitad de temporada (30 dias de juego / 45 dias totales con pre-temporada)
  TRADE_DEADLINE_DAY: 35,
  TRADE_OFFER_EXPIRY_DAYS: 5,
  DERBY_SWINGS_PER_ENTRY: 10,
  DERBY_BASE_HR_PROB: 0.15,
  DERBY_SKILL_COEFFICIENT: 0.006,
  DERBY_MIN_HR_PROB: 0.05,
  DERBY_MAX_HR_PROB: 0.75,
  DERBY_CPU_REWARD_MIN_PCT: 0.5,
  DERBY_CPU_REWARD_MAX_PCT: 1.0,
  DERBY_MAX_TIEBREAK_ROUNDS: 10,
  NEWS_NO_HITTER_MIN_INNINGS: 8,
  NEWS_PERFECT_GAME_MIN_INNINGS: 9,
  NEWS_MULTI_HR_THRESHOLD: 3,
  NEWS_EXTRA_INNINGS_THRESHOLD: 10,
  NEWS_STREAK_MILESTONE: 5,
  NEWS_STREAK_LOOKBACK_GAMES: 50,
};
